### ISSUE TITLE
Missing full Configuration section

### ISSUE THREAD

**Issue by Maco65** [giannello/addon-spotify-connect-librespot#1]
After having troubles with "official" Spotify Add-on I have today installed this one. Thank you !
It work well and better the other one (with the same testing activity).
However in the Configuration section of this Add-on I can only configure Audio Input and Output. The other Configuration options (as described in the Documentation) are not there. :( - see print screen below:
![obraz](https://user-images.githubusercontent.com/18126641/108603274-5a7ff500-73a7-11eb-8745-5b79f6adebcb.png)

I am on latest Core (2021.2.3), Supervisor (2021.02.11) and OS (5.11).

Any ideas why is that and how can I make full Configuration to appear ?

**Comment by giannello** [comment]
I've seen the same behavior in another add-on I'm developing. Looks like the latest version doesn't like an empty `options` map.
Fixed in latest master - make sure to "Reload" in the add-on store.

**Comment by Maco65** [comment]
Confirmed. Working OK.
