### ISSUE TITLE
Addon uses 1 core 100% cpu usage

### ISSUE THREAD

**Issue by gdschut** [giannello/addon-spotify-connect-librespot#2]
Installed this addon, and works nice!
Is it really necessary that this addon uses that much cpu?
It uses 1 core of my RPi4 100%, which is 25% of all cpu %, even when doing nothing and waiting for someone to connect to it.
Hope you can give any tips for lowering this.

**Comment by gdschut** [comment]
after a couple of restarts cpu usage seems to be normal again. Will keep an eye on it...

**Comment by giannello** [comment]
the add-on is only a wrapper to start `librespot`. Issues like this should be reported to the original project.

I'll close the issue now, feel free to reopen it if you think it's necessary.
